site_name: Dataiku Cloud Optimizer Agent
site_description: A Dataiku-driven agent to optimize multi-cloud (AWS, Azure, GCP) and Databricks workloads
site_author: Dataiku Cloud Optimizer Team
site_url: https://omrhamda.github.io/dataiku-cloud-optimizer-agent

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light-blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light-blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_root_heading: true
            show_root_toc_entry: false
            members_order: source

nav:
  - Home: index.md
  - Getting Started:
    - Installation: guides/installation.md
    - Quick Start: guides/quickstart.md
    - Configuration: guides/configuration.md
  - User Guide:
    - CLI Usage: guides/cli.md
    - Cloud Providers: guides/providers.md
    - Optimization Strategies: guides/strategies.md
    - Integrations: guides/integrations.md
  - Examples:
    - Basic Usage: examples/basic.md
    - Advanced Optimization: examples/advanced.md
    - Custom Strategies: examples/custom-strategies.md
  - API Reference:
    - Core: api/core.md
    - Providers: api/providers.md
    - Strategies: api/strategies.md
    - Integrations: api/integrations.md
    - Utilities: api/utils.md
  - Contributing: contributing.md