# Minimal Configuration for Testing

providers:
  aws:
    region: us-east-1
    profile: default

optimization:
  strategies:
    - cost_optimization
    
  thresholds:
    min_savings_percent: 10.0
    min_confidence_score: 0.7

logging:
  level: "INFO"
  
performance:
  concurrency:
    max_workers: 1
  cache:
    enabled: false